spring.application.name=carSearch_backend

openai.api.key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-6-astra}
openai.image.model=${OPENAI_IMAGE_MODEL:gpt-image-1}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
