spring.application.name=carSearch_backend

openai.api.key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-6-astra}
google.search.api.key=${GOOGLE_SEARCH_API_KEY:}
google.search.cx=${GOOGLE_SEARCH_CX:84f8b1981475349c2}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
